export enum EnvVariable {
    CAMUNDA_URL = 'GRIDSOME_CAMUNDA_URL',
    CAMUNDA_PROCESS_ID = 'GRIDSOME_CAMUNDA_PROCESS_ID',
    CAMUNDA_USER = 'GRIDSOME_CAMUNDA_USER',
    CAMUNDA_PASSWORD ='GRIDSOME_CAMUNDA_PASSWORD'
}
